spring:
  security:
    user:
      name: teddy
      password: teddy123
      roles: ADMIN
  datasource:
    url: jdbc:mysql://localhost:3306/gestion_stock?createDatabaseIfNotExist=true
    username: Maximus
    password: Maximus23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

pexels:
  api-key: "cfh1SFTxeNyLrZouc0IrIWCIeFJo76R0J34h2w2v9opZyZJgB3AcvCoT"

# Logging configuration
logging:
  level:
    com.teddy.gestiondestock: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE